import { Department, Doctor, Medicine, LabPackage } from './types';

export const DEPARTMENTS: Department[] = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    description: 'Our Cardiology department offers comprehensive heart care, from preventive screenings to advanced treatments for complex cardiovascular conditions using state-of-the-art diagnostic technology.',
    icon: 'Heart',
    image: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'neurology',
    name: 'Neurology',
    description: 'Specializing in the diagnosis and treatment of all categories of conditions and disease involving the central and peripheral nervous systems, including brain, spinal cord, and cranial nerves.',
    icon: 'Brain',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    description: 'Expert care for musculoskeletal system issues. We specialize in joint replacement, sports medicine, and spinal surgery to help you regain mobility and live a pain-free life.',
    icon: 'Bone',
    image: 'https://images.unsplash.com/photo-1582719471384-894fbb16e074?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    description: 'Providing compassionate healthcare for infants, children, and adolescents. Our pediatricians focus on physical, emotional, and social health from birth through young adulthood.',
    icon: 'Baby',
    image: 'https://images.unsplash.com/photo-1581594634750-7df052118023?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'dermatology',
    name: 'Dermatology',
    description: 'Advanced medical and cosmetic dermatology services. We treat a wide range of skin, hair, and nail conditions, ensuring your skin remains healthy and vibrant.',
    icon: 'Stethoscope',
    image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&q=80&w=800',
  },
];

export const DOCTORS: Doctor[] = [
  {
    id: 'dr-sai',
    name: 'Dr. Sai Theja Bammidi',
    specialty: 'Orthopedic Surgeon',
    departmentId: 'orthopedics',
    experience: 3,
    education: 'MS - Orthopaedics, AIIMS',
    bio: 'Expert in sports medicine and joint replacement surgeries.',
    image: '/dr-sai.jpg',
    hospital: 'A One Hospital, Srikakulam, 532001',
    googleMapsUrl: 'https://maps.app.goo.gl/BopSTSxKmbu1QpZs9',
    availability: {
      'Tuesday': ['10:00', '11:00', '12:00', '15:00'],
      'Thursday': ['09:00', '10:00', '11:00', '14:00'],
    },
  },
];

export const MEDICINES: Medicine[] = [
  {
    id: 'med-1',
    name: 'Dolo 650',
    brandName: 'Dolo',
    genericName: 'Paracetamol',
    category: 'otc',
    composition: 'Paracetamol 650mg',
    indications: 'Fever, Mild to moderate pain relief',
    dosage: '1 tablet every 6 hours as needed. Not more than 4g in 24 hours.',
    sideEffects: ['Nausea', 'Liver damage (in case of overdose)', 'Skin rash'],
    precautions: ['Avoid alcohol', 'Consult if liver issues exist', 'Do not exceed dose'],
    interactions: ['Warfarin', 'Cholestyramine'],
    manufacturer: 'Micro Labs Ltd',
    expiry: '2027-12-31',
    storage: 'Store in a cool, dry place away from sunlight.',
    price: 30.5,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=600',
    prescriptionRequired: false,
    stock: 500,
    symptoms: ['Fever', 'Headache', 'Body Pain'],
    alternatives: [
      { id: 'med-2', name: 'Calpol 650', price: 28.0 }
    ]
  },
  {
    id: 'med-2',
    name: 'Calpol 650',
    brandName: 'Calpol',
    genericName: 'Paracetamol',
    category: 'otc',
    composition: 'Paracetamol 650mg',
    indications: 'Fever, Pain relief',
    dosage: '1 tablet 3-4 times a day.',
    sideEffects: ['Liver toxicity (rare)', 'Allergic reactions'],
    precautions: ['Liver / Kidney disease', 'Pregnancy consultation'],
    interactions: ['Metoclopramide', 'Domperidone'],
    manufacturer: 'GSK',
    expiry: '2026-10-15',
    storage: 'Store below 25°C',
    price: 28.0,
    image: 'https://images.unsplash.com/photo-1631549916768-4119b295f7ef?auto=format&fit=crop&q=80&w=600',
    prescriptionRequired: false,
    stock: 200,
    symptoms: ['Fever', 'Cold'],
  },
  {
    id: 'med-3',
    name: 'Augmentin 625 Duo',
    brandName: 'Augmentin',
    genericName: 'Amoxycillin + Clavulanic Acid',
    category: 'prescription',
    composition: 'Amoxycillin 500mg + Clavulanic Acid 125mg',
    indications: 'Bacterial infections (sinus, pneumonia, ear, skin)',
    dosage: 'Twice daily or as directed by doctor. Complete the full course.',
    sideEffects: ['Diarrhea', 'Nausea', 'Vomiting', 'Yeast infection'],
    precautions: ['Finish full course', 'Penicillin allergy', 'Kidney function'],
    interactions: ['Probenecid', 'Methotrexate'],
    manufacturer: 'GlaxoSmithKline Pharmaceuticals Ltd',
    expiry: '2026-05-20',
    storage: 'Store in a cool dry place.',
    price: 220.75,
    image: 'https://images.unsplash.com/photo-1471864190281-a93fb8869c9d?auto=format&fit=crop&q=80&w=600',
    prescriptionRequired: true,
    stock: 120,
    symptoms: ['Infection', 'Fever', 'Sore Throat'],
  },
  {
    id: 'med-4',
    name: 'Okacet',
    brandName: 'Okacet',
    genericName: 'Cetirizine',
    category: 'otc',
    composition: 'Cetirizine 10mg',
    indications: 'Allergies, Hay fever, Hives',
    dosage: 'One tablet once a day.',
    sideEffects: ['Sleepiness', 'Dry mouth', 'Dizziness'],
    precautions: ['May cause drowsiness', 'Avoid driving', 'Avoid alcohol'],
    interactions: ['Theophylline'],
    manufacturer: 'Cipla Ltd',
    expiry: '2028-01-01',
    storage: 'Store below 30°C',
    price: 18.0,
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=600',
    prescriptionRequired: false,
    stock: 1000,
    symptoms: ['Allergy', 'Sneezing', 'Itching'],
  },
  {
    id: 'med-5',
    name: 'Vicks Vaporub',
    brandName: 'Vicks',
    genericName: 'Menthol + Camphor + Eucalyptus Oil',
    category: 'otc',
    composition: 'Menthol, Camphor, Eucalyptus Oil, Nutmeg Oil, Cedar leaf Oil',
    indications: 'Cough, Cold, Minor muscle aches',
    dosage: 'Rub on chest, neck, and back. Use as needed.',
    sideEffects: ['Skin irritation (rare)'],
    precautions: ['External use only', 'Do not ingest', 'Keep away from eyes'],
    interactions: [],
    manufacturer: 'Procter & Gamble Health Ltd',
    expiry: '2029-06-30',
    storage: 'Keep lid tightly closed. Store in a cool place.',
    price: 155.0,
    image: 'https://images.unsplash.com/photo-1542362567-b034883ede30?auto=format&fit=crop&q=80&w=600',
    prescriptionRequired: false,
    stock: 350,
    symptoms: ['Cold', 'Cough', 'Body Ache'],
  }
];

export const LAB_PACKAGES: LabPackage[] = [
  {
    id: 'lab-1',
    name: 'Diabetic Health Checkup',
    description: 'Get the comprehensive Diabetic Health Checkup plan and maintain your overall health with early detection of complications.',
    parameters: ['HbA1c', 'FBS', 'Lipid Profile', 'Urine Microalbumin'],
    category: 'diabetes',
    image: 'https://images.unsplash.com/photo-1579152276557-8cee2e6c6c2b?auto=format&fit=crop&q=80&w=800',
    sampleRequired: 'Blood, Urine',
    fastingRequired: true,
    preparation: '10-12 hours fasting required',
    isHomeCollectionAvailable: true
  },
  {
    id: 'lab-2',
    name: 'General Health Checkup',
    description: 'A step towards lifelong health with full body checkup to detect and prevent the potential issues in advance.',
    parameters: ['CBC', 'Liver Profile', 'Kidney Profile', 'Glucose'],
    category: 'general',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800',
    sampleRequired: 'Blood',
    fastingRequired: true,
    isHomeCollectionAvailable: true
  },
  {
    id: 'lab-3',
    name: 'Cardiac Profile',
    description: 'Ensuring a healthy heart with thorough evaluation and screening with our complete Cardiac Profile for risk elimination.',
    parameters: ['ECG', 'ECHO', 'Lipid Profile', 'TMT'],
    category: 'cardiac',
    image: 'https://images.unsplash.com/photo-1628348017897-42a174351329?auto=format&fit=crop&q=80&w=800',
    sampleRequired: 'Blood, Imaging',
    fastingRequired: false,
    isHomeCollectionAvailable: false
  },
  {
    id: 'lab-4',
    name: 'Executive Health Checkup (Female)',
    description: 'Promoting healthy life and wellness to all the women with our extensive health checkup plan curated especially for females.',
    parameters: ['Pap Smear', 'Mammography', 'Thyroid Profile', 'Vitamin D'],
    category: 'women',
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&q=80&w=800',
    sampleRequired: 'Blood, Swab',
    fastingRequired: true,
    isHomeCollectionAvailable: true
  },
  {
    id: 'lab-5',
    name: 'Renal (Kidney) Health Checkup',
    description: 'Detect the signs of risk and get the preventive tips for maintaining the health of your kidneys.',
    parameters: ['Creatinine', 'BUN', 'Uric Acid', 'Electrolytes'],
    category: 'renal',
    image: 'https://images.unsplash.com/photo-1559133965-f81d92ee655c?auto=format&fit=crop&q=80&w=800',
    sampleRequired: 'Blood, Urine',
    fastingRequired: true,
    isHomeCollectionAvailable: true
  }
];
